### ISSUE TITLE
Select-style multi select

### ISSUE THREAD

**Issue by adambedford** [cibernox/ember-power-select#1014]
Is there a straightforward way to mimic multi-select functionality such as [bootstrap-select](https://silviomoreto.github.io/bootstrap-select/examples/#multiple-select-boxes) without overriding the entire `optionsComponent` -- it looks like I'd have to copy/paste `options.hbs` and make some small tweaks, but that isn't all public API.

![image](https://user-images.githubusercontent.com/1626169/32618177-d1568226-c52b-11e7-8b62-1e62369ced65.png)

**Comment by cibernox** [comment]
If what you want to do is only add that icon, I'd just CSS on the class `.ember-power-select-option[aria-selected="true"]`.
```css
.ember-power-select-option[aria-selected="true"]::after {
  font-family: 'MyIconsFont';
  content: '✓'
}
```

However you do can override the template of the options component if you have to, the values in those templates are public API too.
