### ISSUE TITLE
Dropdown positioning problem

### ISSUE THREAD

**Issue by nhemanth007** [cibernox/ember-power-select#321]
When component is not rendered in place, dropdown is appended to div with id `ember-basic-dropdown-wormhole` which is added to body. In my use case, body is not scrollable and a section of the body is scrollable in which power select is used. In this scenario when scrollable section is scrolled, trigger scrolls with the scrollable section, but dropdown doesn't scroll along with trigger as it is positioned absolute(parent element is body). If select is at the bottom of the section and rendered in place, dropdown goes down(There is no auto positioning for render in place).

**Comment by mangatinanda** [comment]
@nhemanth007 @cibernox Here is my suggestion.

Normal browser select won't allow you to scroll when it is open until you select some option or close it.

We can achieve similar behaviour if `body` is locked down to available browser height. When the dropdown is open `#ember-basic-dropdown-wormhole` element can have following css properties to prevent any other scrolls until the power select is closed.
```css
#ember-basic-dropdown-wormhole.is-dropdown-open {
  position:absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  z-index: 999;  // less than dropdown z-index to have it on top.
}
```
