### ISSUE TITLE
Bootstrap styling

### ISSUE THREAD

**Issue by ksnyde** [cibernox/ember-power-select#477]
I'm using Bootstrap 4 with the following in my `app.scss`:

``` css
@import 'ember-power-select/themes/bootstrap';
@import 'ember-power-select';
@import 'bootstrap-flex';
```

Initially when I dropped this into a template it was pretty broken:

![broken-dropdown](https://cloud.githubusercontent.com/assets/980757/14941626/cb10648e-0f99-11e6-8a7d-c5f2dccf90c9.gif)

But then I added the following lines of CSS to get it semi-fixed:

``` css
  .ember-power-select {
    width: 100%;
    align-self: center;
  }
```

Which made the initial loading state but there is still a height disparity with other BS controls:

![spaced-but-wrong height](https://cloud.githubusercontent.com/assets/980757/14941650/3650b126-0f9b-11e6-9c68-e802aa8f7ed5.gif)

Then I added the following CSS:

``` css
  .ember-power-select-trigger {
    padding: 2px 16px 2px 8px;
  }
```

Which works for the situations where something is selected but when _nothing_ is selected there is no trigger target and therefore I don't get the padding boost I need. I guess this was by design but it does feel sort of right that there would always be a trigger selector, doesn't it?

Regardless I think the import mixin you provide should address this somehow.

![semi-fixed-downdown](https://cloud.githubusercontent.com/assets/980757/14941668/dd57be6a-0f9b-11e6-827d-8d6f91a4af43.gif)

**Comment by ksnyde** [comment]
For now I've solved it with:

```css
  .ember-power-select-trigger {
    display: flex;
    align-items: center;
    height: 38px;
  }
```

but don't love the pixel based height parameter as it's a bit too brittle.
