### ISSUE TITLE
How to create two EPS with different list-item CSS but the same selected-item CSS?

### ISSUE THREAD

**Issue by ayuk23** [cibernox/ember-power-select#663]
I understand that normally you could just change the Handlebars that comes after the {{#power-select}} and before the {{/power-select}}, but doing so also changes the way the item is rendered in the input box. How could I handle creating two different selectors that render the items in the dropdown differently, while rendering the selected-items the same?

**Comment by cibernox** [comment]
Add some class to the dropdown:

```hbs
{{#power-select options=... selected=... dropdownClass="with-orange-text" as |opt|}}
  {{opt}}
{{/power-select}}
```

```css
.ember-power-select-content.with-orange-text .ember-power-select-option {
  color: orange;
}
```

Makes sense?
