### ISSUE TITLE
CSS issues inside of Flexbox

### ISSUE THREAD

**Issue by elwayman02** [cibernox/ember-power-select#82]
CSS:
```scss
.container {
  align-items: center;
  display: flex;
  flex-direction: row;
}
```
HBS:
```handlebars
<div class="container">
    <span>Search By:</span>
    {{#ember-power-select
    onchange=(action (mut searchKey))
    options=searchTypes
    selected=searchKey
    as |type|}}
        {{type.label}}
    {{/ember-power-select}}
</div>
```
Screenshot:
<img width="205" alt="ember_data_echonest_demo" src="https://cloud.githubusercontent.com/assets/1325482/10852855/4e9c7b16-7ef0-11e5-84f9-4a995d4b5f4f.png">
